### ISSUE TITLE
Not all dimensions shown

### ISSUE THREAD

**Issue by NFDWADM** [SimoneSilini/Reboot-Timeline#2]
The extension shows "only" 12 dimensions, can this be bumped up to more?

**Comment by ZiedAhmed99** [comment]
![trythis](https://user-images.githubusercontent.com/44872851/70233984-f05a4080-175f-11ea-8882-1309ad08b36f.PNG)
try this bro

**Comment by SimoneSilini** [comment]
This is not possible - This graph is based on the Google timeline chart, so the functions are limited to that library.
