### ISSUE TITLE
Color issue on dimension

### ISSUE THREAD

**Issue by SumitGarg1995** [SimoneSilini/Reboot-Timeline#3]
Hello, Facing issues with extension can't able to select different colors on the dimension field and also not getting the add dimension option after adding the 4th dimension. The solution I'm looking for is that I  want to replace the green color with multicolors.
![Screenshot (19)](https://user-images.githubusercontent.com/50099813/56884650-1449fb00-6a88-11e9-8021-86c4545ae5ad.png)

**Comment by ZiedAhmed99** [comment]
Hello No you can bro : 
You  just only to add a dimension (Dimension number 3  like this for example : 

=if([Task RAG Status] ='Green','#00936f',

if([Task RAG Status]='Yellow','#ffcf02',

if([Task RAG Status]= 'Red','#FF6961',



     '#B8B8B5'

)



))

)
