### ISSUE TITLE
Missing Prefix in the path

### ISSUE THREAD

**Issue by TT-66** [SimoneSilini/Reboot-Timeline#4]
Hi, 

I tried your great extention on Qlik Sense Desktop. After good appreciation, I upload the extension in our server (via QMC).

Using the extension online doesn't work, I've a error message on the visualization.

Looking into the log on the browser. The 'get' path is missing the prefix. See attachement.

On the server we use different extensions that work fine.

Can you help me with this issue?

Best regards

![error missing prefix](https://user-images.githubusercontent.com/50867819/58086553-2dddee80-7bbf-11e9-84c8-39f7da49d2ec.png)

**Comment by SimoneSilini** [comment]
Hi, 

it seems that you haven't on your server the file goog.js, that should be inside my extension as well so maybe it has been loaded in a different folder, you might want to check your servers for file locations and either move the file or update the link
