### ISSUE TITLE
Adding vertical "Reference Line" 

### ISSUE THREAD

**Issue by JanceKayre** [SimoneSilini/Reboot-Timeline#5]
Hi Simone,

I would have created this bug more like an enhancement, but I could only create it like this.
I have 2 questions :

Is it possible that you add a vertical line through the all visual ? To see for instance, the date of today. It would be nice to set the date and the color of the vertical line.
Is it also possible to add a zoom on the period (X-axis) with the mouse wheel ? Some periods are too small to see.
Though, your extension is working perfectly !

Regards, Jance Kayre

**Comment by SirGarnet** [comment]
Hi Jance,

I can answer you questions:

1. & 2. This is not possible - This graph is based on the Google timeline chart, so the functions are limited to that library.

Regards
SirGarnet

**Comment by JanceKayre** [comment]
Hi SirGarnet,

Thanks for the info.
I hoped that this was possible because I have many users asking for this function inside the visual.

But you can't implement it if it's blocked by the library.

Thanks again !
