### ISSUE TITLE
Vertical reference line

### ISSUE THREAD

**Issue by SiO2y** [SimoneSilini/Reboot-Timeline#6]
Fantastic extension, works really well and presents data beautifully.
Would it be possible to implement a feature to add a vertical 'reference line' (or lines) based on either static dates or dynamic dates e.g. Today( ) or Min( [Start_Date] ) ?
Thanks

**Comment by SirGarnet** [comment]
Hi take a look at the closed issue #5

Greetings
SirGarnet

**Comment by SiO2y** [comment]
Thank you. So sorry. I looked through the open issues and didn't see the closed issues section. My bad. Thanks for this again.
