### ISSUE TITLE
reference line with today date 

### ISSUE THREAD

**Issue by ZiedAhmed99** [SimoneSilini/Reboot-Timeline#7]
Hello
Can you please show us how to add a reference line (vertical line for today date)

Thanks

**Comment by SiO2y** [comment]
It isn't possible. See here for the reason: https://github.com/SimoneSilini/Reboot-Timeline/issues/5#issuecomment-528782068

**Comment by ZiedAhmed99** [comment]
ok bro what about extrat this with pdf ? is this possible ? 

Thanks

**Comment by SimoneSilini** [comment]
This is not possible - This graph is based on the Google timeline chart, so the functions are limited to that library.
