### ISSUE TITLE
Invalid Extension

### ISSUE THREAD

**Issue by iboy-geek** [SimoneSilini/Reboot-Timeline#9]
Even I am also facing the same issue it's showing invalid Visualization and I am using it on my `prod environment` and `local environment`. 
can any please post the answer its problem came to my bottleneck. Thanks in advance
![image](https://user-images.githubusercontent.com/67047634/84876141-858da880-b0a4-11ea-910a-1478324818ac.png)

**Comment by SimoneSilini** [comment]
Hi, new version online.

The problem has been fixed.

**Comment by CamisLima** [comment]
Hi @SimoneSilini ,

The version here in Github is still withe the same issue.

**Comment by SimoneSilini** [comment]
Hi mate, try it now :)
